title=("Program 'game over' 2.0")
print("same",'message',"as\n before")
print("Here",end="  ")
print("it is. . .")
print("""
GAME OVER""")
print("\t\t\tfancy  T")
print("pie"*5)
print(110/3)
print(110//3)
print(110%3)
print("\t\t\t\t",title.upper())
print(title.capitalize())
print(title.swapcase())
print(title.title())
print(title.strip( " d"))